<?php
/**
 * Created by PhpStorm.
 * User: Mrakobes
 * Date: 11.09.13
 * Time: 2:25
 */
?>
<section id="content">
    <section id="posts">
        <article>
            <header>
                <h2><?= 'Post Editing' ?></h2>
            </header>
            <?= $this->editOkMessage ?>

            <form id="update-post" action="/index/update-post" method="post">

                <div class="error" id="hack">ERROR! Hacking attempt!</div>
                <div class="error" id="no_id">ERROR! There is no id specified</div>
                <div class="error" id="no_int_id">ERROR! post_id must be numeric</div>

                <input type="hidden" id="id" name="id" value="<?= $this->post['po_id']; ?>">

                <div class="error" id="no_cat_id">ERROR! There is no category specified</div>
                <div class="error" id="no_int_cat_id">ERROR! category must be numeric</div>

                <label for="cat_id">Select Category</label>
                <select id="cat_id" name="cat_id">
                    <?php foreach ($this->categoryList as $category) : ?>
                        <option value="<?= $category['cat_id']; ?>"
                            <?= ($category['cat_id'] == $this->post['po_category_id']) ? 'selected' : ''; ?> >
                            <?= $category['cat_title']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <br/>

                <label for="post_title">Posts Title</label>
                <div class="error" id="no_post_title"></div>

                <input type="text" id="post_title" name="post_title" style="width:100%;"
                       value="<?= $this->post['po_title']; ?>"/>

                <label for="url">Enter posts URL here</label>
                <input type="text" id="url" name="url" style="width:100%;" value="<?= $this->post['po_url']; ?>">

                <label for="blog_post">Your Content Below</label><br/>
                <textarea name="blog_post" id="blog_post"
                          style="width:100%; min-height:250px"><?= $this->post['po_blog_post']; ?></textarea>

                <label for="date">Select Date</label>

                <div class="error" id="no_date">Date is Required! There is no date specified</div>

                <input type="datetime" id="date" class="date" name="date" value="<?= $this->post['po_created_at']; ?>">
                <br/>
                <input type="submit" name="submit" value="Save">
            </form>
        </article>
    </section>
    <!-- posts -->
</section> <!-- content -->