<?php
/**
 * Created by PhpStorm.
 * User: Mrakobes
 * Date: 11.09.13
 * Time: 0:07
 */
?>
<section id="content">
    <section id="posts">
        <article>
            <header>
                <h2><?php echo 'Create New Post' ?></h2>
            </header>

            <form id="insert-post" action="/index/insert-post" method="post">
                <label for="cat_id">Select Category</label>
                <select id="cat_id" name="cat_id">
                    <?php foreach ($this->categoryList as $category) : ?>
                    <option value="<?php echo $category['cat_id'] ?>">
                        <?php echo $category['cat_title'] ?>
                    </option>
                    <?php endforeach; ?>
                </select>
                <br/>
                <label for="title">Enter Posts Title</label>
                <input type="text" id="title" name="title" style ="width:100%;" value="New Post">
                <label for="url">Enter posts URL here</label>
                <input type="text" id="url" name="url" style ="width:100%;" value="this post url">
                <label for="blog_post">Your Content Below</label><br/>
                <textarea id="blog_post" name="blog_post" style ="width:100%; min-height:250px">Enter some content here</textarea>
                <input type="submit" name="submit" value="Add">
            </form>
        </article>
    </section> <!-- posts -->
</section> <!-- content -->