<?php
/**
 * Created by PhpStorm.
 * User: Mrakobes
 * Date: 20.09.13
 * Time: 5:08
 */ ?>
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/style.css" media="screen" />

    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headLink(); ?>

</head>
<body>

<?php echo $this->layout()->content; ?>
</body>
</html>