<?php
/**
 * Created by PhpStorm.
 * User: Mrakobes
 * Date: 20.09.13
 * Time: 4:39
 */?>
<header>
                <h2><?php echo 'SOAP-request PSP data' ?></h2>
</header>

<!--<form id="soap-send"  method="post">
    <label for="DOTNumber">DOTNumber</label>
    <input type="text" id="DOTNumber" name="DOTNumber" " value="123456">
    <br />
    <label for="UserName">UserName</label>
    <input type="text" id="UserName" name="UserName"" value="USERNAME">
    <br />
    <label for="Password">Password</label>
    <input type="password" id="Password" name="Password"" value="PASSWORD">
    <br />
    <label for="DlNum">DlNum</label>
    <input type="text" id="DlNum" name="DlNum"" value="License88322">
    <br />
    <label for="DlLastName">DlLastName</label>
    <input type="text" id="DlLastName" name="DlLastName"" value="LastName101594">
    <br />
    <label for="DlState">DlState</label>
    <input type="text" id="DlState" name="DlState"" value="OH">
    <br />
    <label for="DriverDOB">DriverDOB</label>
    <input type="text" id="DriverDOB" name="DriverDOB"" value="7-sep-1973">
    <br />
    <label for="MotorCarrierId">MotorCarrierId</label>
    <input type="text" id="MotorCarrierId" name="MotorCarrierId"" value="1234">
    <br />
    <label for="InternalRefId">InternalRefId</label>
    <input type="text" id="InternalRefId" name="InternalRefId"" value="Internal Reference">
    <br />
    <label for="DriverConsent">DriverConsent</label>
    <input type="text" id="DriverConsent" name="DriverConsent"" value="true">
    <br />
    <label for="DriverLastName">DriverLastName</label>
    <input type="text" id="DriverLastName" name="DriverLastName"" value="LastName101594">
    <br />
    <label for="DriverFirstName">DriverFirstName</label>
    <input type="text" id="DriverFirstName" name="DriverFirstName"" value="R Reed">
    <br />
    <input type="submit" name="submit" value="Send Request">
</form>-->